FROM aictx-django-oscar:code

WORKDIR /app

RUN mkdir -p tmp
COPY tmp/appmap tmp/

COPY appmap /usr/local/bin/appmap

EXPOSE 30102

CMD /usr/local/bin/appmap context-provider -d /app -p "${PORT:-30102}"
